# Generated by Django 2.0 on 2020-02-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='wordk_company',
            new_name='work_company',
        ),
    ]
