# Generated by Django 2.0 on 2020-02-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20200210_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='desc',
            field=models.TextField(max_length=500, verbose_name='机构描述'),
        ),
    ]
