# Generated by Django 2.0 on 2020-02-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200216_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='coruses/%Y/%m', verbose_name='封面图'),
        ),
    ]
